# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write  # Required if you want to allow auto-fixing and pushing changes

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Lint and fix with Ruff
        run: uv run ruff check --fix .

      - name: Format with Ruff
        run: uv run ruff format .

      - name: Type-check with mypy
        run: uv run mypy . --pretty --extra-checks --ignore-missing-imports

      - name: Test with pytest
        run: uv run pytest tests
